import "dotenv/config";
import { PrismaClient } from "../lib/generated/prisma/client";
import { PrismaLibSql } from "@prisma/adapter-libsql";

const adapter = new PrismaLibSql({ url: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const DIET_TAGS = ["Vegetarian", "Vegan", "HighProtein", "LowCarb", "QuickMeal"] as const;

const INGREDIENTS = [
  // Proteins
  { name: "Chicken Breast", category: "protein" },
  { name: "Chicken Thigh", category: "protein" },
  { name: "Ground Chicken", category: "protein" },
  { name: "Salmon", category: "protein" },
  { name: "Tuna", category: "protein" },
  { name: "Shrimp", category: "protein" },
  { name: "Cod", category: "protein" },
  { name: "Tilapia", category: "protein" },
  { name: "Eggs", category: "protein" },
  { name: "Tofu", category: "protein" },
  { name: "Tempeh", category: "protein" },
  { name: "Black Beans", category: "protein" },
  { name: "Lentils", category: "protein" },
  { name: "Chickpeas", category: "protein" },
  // Vegetables
  { name: "Broccoli", category: "vegetable" },
  { name: "Spinach", category: "vegetable" },
  { name: "Bell Pepper", category: "vegetable" },
  { name: "Onion", category: "vegetable" },
  { name: "Garlic", category: "vegetable" },
  { name: "Tomato", category: "vegetable" },
  { name: "Zucchini", category: "vegetable" },
  { name: "Mushrooms", category: "vegetable" },
  { name: "Carrot", category: "vegetable" },
  { name: "Sweet Potato", category: "vegetable" },
  { name: "Kale", category: "vegetable" },
  { name: "Cucumber", category: "vegetable" },
  { name: "Avocado", category: "vegetable" },
  { name: "Corn", category: "vegetable" },
  { name: "Green Beans", category: "vegetable" },
  { name: "Cauliflower", category: "vegetable" },
  { name: "Asparagus", category: "vegetable" },
  { name: "Cabbage", category: "vegetable" },
  // Carbs
  { name: "Rice", category: "carb" },
  { name: "Brown Rice", category: "carb" },
  { name: "Pasta", category: "carb" },
  { name: "Quinoa", category: "carb" },
  { name: "Bread", category: "carb" },
  { name: "Tortilla", category: "carb" },
  { name: "Noodles", category: "carb" },
  { name: "Oats", category: "carb" },
  { name: "Potato", category: "carb" },
  // Other
  { name: "Olive Oil", category: "other" },
  { name: "Soy Sauce", category: "other" },
  { name: "Lemon", category: "other" },
  { name: "Lime", category: "other" },
  { name: "Ginger", category: "other" },
  { name: "Coconut Milk", category: "other" },
  { name: "Greek Yogurt", category: "other" },
  { name: "Cheese", category: "other" },
  { name: "Honey", category: "other" },
  { name: "Sesame Oil", category: "other" },
  { name: "Rice Vinegar", category: "other" },
  { name: "Cumin", category: "other" },
  { name: "Paprika", category: "other" },
  { name: "Chili Flakes", category: "other" },
  { name: "Basil", category: "other" },
  { name: "Cilantro", category: "other" },
  { name: "Parsley", category: "other" },
];

interface RecipeSeed {
  name: string;
  description: string;
  prepTime: number;
  calories: number;
  difficulty: string;
  instructions: string;
  dietTags: string[];
  ingredients: { name: string; required: boolean }[];
}

const RECIPES: RecipeSeed[] = [
  // === CHICKEN (20) ===
  {
    name: "Lemon Herb Grilled Chicken",
    description: "Juicy grilled chicken breast marinated in lemon and fresh herbs.",
    prepTime: 25,
    calories: 320,
    difficulty: "Easy",
    instructions: "Marinate chicken in lemon juice, olive oil, garlic, and herbs for 20 min. Grill 6-7 min per side until internal temp reaches 165°F. Rest 5 min before slicing.",
    dietTags: ["HighProtein", "LowCarb", "QuickMeal"],
    ingredients: [
      { name: "Chicken Breast", required: true },
      { name: "Lemon", required: true },
      { name: "Olive Oil", required: true },
      { name: "Garlic", required: true },
      { name: "Parsley", required: false },
    ],
  },
  {
    name: "Chicken Stir-Fry with Broccoli",
    description: "Quick weeknight stir-fry with tender chicken and crisp broccoli.",
    prepTime: 20,
    calories: 380,
    difficulty: "Easy",
    instructions: "Slice chicken into strips. Stir-fry in sesame oil 4-5 min. Add broccoli and bell pepper, cook 3 min. Add soy sauce and ginger, toss to combine.",
    dietTags: ["HighProtein", "QuickMeal"],
    ingredients: [
      { name: "Chicken Breast", required: true },
      { name: "Broccoli", required: true },
      { name: "Bell Pepper", required: true },
      { name: "Soy Sauce", required: true },
      { name: "Sesame Oil", required: true },
      { name: "Ginger", required: false },
      { name: "Rice", required: false },
    ],
  },
  {
    name: "Chicken and Quinoa Bowl",
    description: "Nutrient-packed bowl with seasoned chicken, quinoa, and fresh veggies.",
    prepTime: 30,
    calories: 450,
    difficulty: "Easy",
    instructions: "Cook quinoa per package directions. Season chicken with cumin and paprika, pan-sear 6 min per side. Slice and serve over quinoa with avocado, tomato, and corn.",
    dietTags: ["HighProtein"],
    ingredients: [
      { name: "Chicken Breast", required: true },
      { name: "Quinoa", required: true },
      { name: "Avocado", required: true },
      { name: "Tomato", required: false },
      { name: "Corn", required: false },
      { name: "Cumin", required: false },
    ],
  },
  {
    name: "Creamy Garlic Chicken Pasta",
    description: "Comfort food classic with a lighter garlic cream sauce.",
    prepTime: 30,
    calories: 520,
    difficulty: "Medium",
    instructions: "Cook pasta al dente. Sauté sliced chicken in olive oil until golden. Add garlic, cook 1 min. Stir in Greek yogurt and spinach. Toss with pasta.",
    dietTags: [],
    ingredients: [
      { name: "Chicken Breast", required: true },
      { name: "Pasta", required: true },
      { name: "Garlic", required: true },
      { name: "Greek Yogurt", required: true },
      { name: "Spinach", required: true },
      { name: "Olive Oil", required: false },
    ],
  },
  {
    name: "Chicken Fajitas",
    description: "Sizzling chicken fajitas with colorful peppers and warm tortillas.",
    prepTime: 25,
    calories: 420,
    difficulty: "Easy",
    instructions: "Slice chicken and peppers into strips. Cook chicken in hot pan 5 min. Add peppers and onion, cook 4 min. Season with cumin and chili. Serve in tortillas.",
    dietTags: ["HighProtein", "QuickMeal"],
    ingredients: [
      { name: "Chicken Breast", required: true },
      { name: "Bell Pepper", required: true },
      { name: "Onion", required: true },
      { name: "Tortilla", required: true },
      { name: "Cumin", required: false },
      { name: "Lime", required: false },
    ],
  },
  {
    name: "Honey Garlic Chicken Thighs",
    description: "Caramelized chicken thighs glazed with honey and garlic.",
    prepTime: 35,
    calories: 480,
    difficulty: "Easy",
    instructions: "Season thighs with salt and pepper. Sear skin-side down 7 min, flip 5 min. Mix honey, soy sauce, garlic. Pour over chicken, bake at 400°F for 15 min.",
    dietTags: ["HighProtein"],
    ingredients: [
      { name: "Chicken Thigh", required: true },
      { name: "Honey", required: true },
      { name: "Garlic", required: true },
      { name: "Soy Sauce", required: true },
      { name: "Rice", required: false },
    ],
  },
  {
    name: "Chicken and Sweet Potato Sheet Pan",
    description: "One-pan roasted chicken with caramelized sweet potatoes.",
    prepTime: 40,
    calories: 410,
    difficulty: "Easy",
    instructions: "Cube sweet potatoes and toss with olive oil, paprika. Spread on sheet pan with chicken thighs. Roast at 425°F for 30 min. Add green beans last 10 min.",
    dietTags: ["HighProtein", "LowCarb"],
    ingredients: [
      { name: "Chicken Thigh", required: true },
      { name: "Sweet Potato", required: true },
      { name: "Green Beans", required: true },
      { name: "Olive Oil", required: true },
      { name: "Paprika", required: false },
    ],
  },
  {
    name: "Thai Chicken Coconut Curry",
    description: "Rich and aromatic coconut curry with tender chicken pieces.",
    prepTime: 35,
    calories: 490,
    difficulty: "Medium",
    instructions: "Sauté onion and garlic 3 min. Add cubed chicken, cook 5 min. Pour in coconut milk, add ginger and chili flakes. Simmer 15 min. Stir in spinach, serve over rice.",
    dietTags: ["HighProtein"],
    ingredients: [
      { name: "Chicken Thigh", required: true },
      { name: "Coconut Milk", required: true },
      { name: "Spinach", required: true },
      { name: "Onion", required: true },
      { name: "Garlic", required: true },
      { name: "Ginger", required: true },
      { name: "Rice", required: false },
    ],
  },
  {
    name: "Chicken Caesar Lettuce Wraps",
    description: "Low-carb twist on chicken Caesar with crunchy lettuce cups.",
    prepTime: 15,
    calories: 290,
    difficulty: "Easy",
    instructions: "Grill chicken breast, slice thin. Mix Greek yogurt with lemon juice and garlic for dressing. Fill lettuce cups with chicken, drizzle dressing, top with cheese.",
    dietTags: ["HighProtein", "LowCarb", "QuickMeal"],
    ingredients: [
      { name: "Chicken Breast", required: true },
      { name: "Greek Yogurt", required: true },
      { name: "Lemon", required: true },
      { name: "Garlic", required: true },
      { name: "Cheese", required: false },
    ],
  },
  {
    name: "Chicken Teriyaki Rice Bowl",
    description: "Sweet and savory teriyaki chicken over steamed rice.",
    prepTime: 25,
    calories: 510,
    difficulty: "Easy",
    instructions: "Cook rice. Mix soy sauce, honey, rice vinegar, and ginger for teriyaki sauce. Pan-fry chicken strips 5 min. Add sauce, simmer until glazed. Serve over rice with broccoli.",
    dietTags: ["HighProtein"],
    ingredients: [
      { name: "Chicken Breast", required: true },
      { name: "Rice", required: true },
      { name: "Soy Sauce", required: true },
      { name: "Honey", required: true },
      { name: "Rice Vinegar", required: true },
      { name: "Broccoli", required: false },
      { name: "Ginger", required: false },
    ],
  },
  {
    name: "Ground Chicken Lettuce Cups",
    description: "Asian-inspired ground chicken in crisp lettuce cups.",
    prepTime: 15,
    calories: 310,
    difficulty: "Easy",
    instructions: "Brown ground chicken with ginger and garlic. Add soy sauce, rice vinegar, sesame oil. Cook 2 min. Spoon into lettuce cups. Top with cilantro and chili flakes.",
    dietTags: ["HighProtein", "LowCarb", "QuickMeal"],
    ingredients: [
      { name: "Ground Chicken", required: true },
      { name: "Soy Sauce", required: true },
      { name: "Ginger", required: true },
      { name: "Garlic", required: true },
      { name: "Sesame Oil", required: true },
      { name: "Cilantro", required: false },
    ],
  },
  {
    name: "Chicken and Vegetable Soup",
    description: "Hearty homestyle chicken soup loaded with fresh vegetables.",
    prepTime: 40,
    calories: 280,
    difficulty: "Easy",
    instructions: "Sauté onion, carrot, garlic in olive oil. Add cubed chicken, cook 5 min. Add water, bring to boil. Add potato and green beans, simmer 20 min until tender.",
    dietTags: ["HighProtein", "LowCarb"],
    ingredients: [
      { name: "Chicken Breast", required: true },
      { name: "Carrot", required: true },
      { name: "Potato", required: true },
      { name: "Onion", required: true },
      { name: "Green Beans", required: true },
      { name: "Garlic", required: false },
    ],
  },
  {
    name: "Spicy Chicken Noodle Stir-Fry",
    description: "Spicy noodles tossed with chicken and crunchy vegetables.",
    prepTime: 20,
    calories: 460,
    difficulty: "Easy",
    instructions: "Cook noodles, drain. Stir-fry chicken strips in sesame oil 4 min. Add mushrooms and cabbage, cook 3 min. Toss in noodles with soy sauce and chili flakes.",
    dietTags: ["HighProtein", "QuickMeal"],
    ingredients: [
      { name: "Chicken Breast", required: true },
      { name: "Noodles", required: true },
      { name: "Mushrooms", required: true },
      { name: "Cabbage", required: true },
      { name: "Soy Sauce", required: true },
      { name: "Chili Flakes", required: false },
      { name: "Sesame Oil", required: false },
    ],
  },
  {
    name: "Chicken Burrito Bowl",
    description: "Deconstructed burrito with seasoned chicken and fresh toppings.",
    prepTime: 30,
    calories: 530,
    difficulty: "Easy",
    instructions: "Season chicken with cumin and paprika, grill 6 min per side. Cook brown rice. Assemble bowls with rice, sliced chicken, black beans, corn, avocado, and lime.",
    dietTags: ["HighProtein"],
    ingredients: [
      { name: "Chicken Breast", required: true },
      { name: "Brown Rice", required: true },
      { name: "Black Beans", required: true },
      { name: "Avocado", required: true },
      { name: "Corn", required: false },
      { name: "Lime", required: false },
      { name: "Cumin", required: false },
    ],
  },
  {
    name: "Chicken Caprese Bake",
    description: "Baked chicken topped with fresh tomato, basil, and melted cheese.",
    prepTime: 30,
    calories: 390,
    difficulty: "Easy",
    instructions: "Pound chicken breasts to even thickness. Season and place in baking dish. Top with sliced tomato, cheese, and basil. Bake at 375°F for 22 min.",
    dietTags: ["HighProtein", "LowCarb"],
    ingredients: [
      { name: "Chicken Breast", required: true },
      { name: "Tomato", required: true },
      { name: "Cheese", required: true },
      { name: "Basil", required: true },
      { name: "Olive Oil", required: false },
    ],
  },
  {
    name: "Chicken Fried Rice",
    description: "Better-than-takeout chicken fried rice with scrambled eggs.",
    prepTime: 20,
    calories: 470,
    difficulty: "Easy",
    instructions: "Scramble eggs, set aside. Stir-fry diced chicken 5 min. Add cold rice, soy sauce, sesame oil. Push to side, add carrot and corn. Combine all with eggs.",
    dietTags: ["HighProtein", "QuickMeal"],
    ingredients: [
      { name: "Chicken Breast", required: true },
      { name: "Rice", required: true },
      { name: "Eggs", required: true },
      { name: "Soy Sauce", required: true },
      { name: "Carrot", required: false },
      { name: "Corn", required: false },
      { name: "Sesame Oil", required: false },
    ],
  },
  {
    name: "Chicken Zucchini Boats",
    description: "Stuffed zucchini halves filled with seasoned ground chicken.",
    prepTime: 35,
    calories: 340,
    difficulty: "Medium",
    instructions: "Halve zucchini, scoop out centers. Brown ground chicken with onion, garlic, and tomato. Fill zucchini halves, top with cheese. Bake at 375°F for 20 min.",
    dietTags: ["HighProtein", "LowCarb"],
    ingredients: [
      { name: "Ground Chicken", required: true },
      { name: "Zucchini", required: true },
      { name: "Tomato", required: true },
      { name: "Onion", required: true },
      { name: "Cheese", required: true },
      { name: "Garlic", required: false },
    ],
  },
  {
    name: "Chicken and Asparagus Skillet",
    description: "One-pan lemon chicken with crisp-tender asparagus.",
    prepTime: 20,
    calories: 330,
    difficulty: "Easy",
    instructions: "Sear chicken in olive oil 6 min per side, remove. Add asparagus, cook 4 min. Return chicken, add lemon juice and garlic. Cover 3 min to finish.",
    dietTags: ["HighProtein", "LowCarb", "QuickMeal"],
    ingredients: [
      { name: "Chicken Breast", required: true },
      { name: "Asparagus", required: true },
      { name: "Lemon", required: true },
      { name: "Olive Oil", required: true },
      { name: "Garlic", required: false },
    ],
  },
  {
    name: "Chicken Tikka Masala",
    description: "Creamy spiced tomato sauce with tender marinated chicken.",
    prepTime: 45,
    calories: 480,
    difficulty: "Medium",
    instructions: "Marinate chicken in yogurt and spices 30 min. Grill or broil until charred. Sauté onion, garlic, ginger. Add tomato and coconut milk, simmer 15 min. Add chicken.",
    dietTags: ["HighProtein"],
    ingredients: [
      { name: "Chicken Thigh", required: true },
      { name: "Greek Yogurt", required: true },
      { name: "Tomato", required: true },
      { name: "Coconut Milk", required: true },
      { name: "Onion", required: true },
      { name: "Ginger", required: true },
      { name: "Garlic", required: true },
      { name: "Rice", required: false },
    ],
  },
  {
    name: "Chicken Cauliflower Rice Bowl",
    description: "Low-carb bowl with riced cauliflower and grilled chicken.",
    prepTime: 20,
    calories: 310,
    difficulty: "Easy",
    instructions: "Pulse cauliflower in food processor. Sauté in olive oil 5 min. Grill seasoned chicken, slice. Serve chicken over cauliflower rice with avocado and lime.",
    dietTags: ["HighProtein", "LowCarb", "QuickMeal"],
    ingredients: [
      { name: "Chicken Breast", required: true },
      { name: "Cauliflower", required: true },
      { name: "Avocado", required: true },
      { name: "Olive Oil", required: true },
      { name: "Lime", required: false },
    ],
  },

  // === VEGETARIAN (10) ===
  {
    name: "Vegetable Quinoa Stir-Fry",
    description: "Protein-rich quinoa tossed with seasonal vegetables.",
    prepTime: 25,
    calories: 380,
    difficulty: "Easy",
    instructions: "Cook quinoa. Stir-fry bell pepper, broccoli, mushrooms, and carrot in sesame oil 5 min. Add cooked quinoa, soy sauce, and ginger. Toss to combine.",
    dietTags: ["Vegetarian", "Vegan"],
    ingredients: [
      { name: "Quinoa", required: true },
      { name: "Bell Pepper", required: true },
      { name: "Broccoli", required: true },
      { name: "Mushrooms", required: true },
      { name: "Soy Sauce", required: true },
      { name: "Sesame Oil", required: false },
      { name: "Carrot", required: false },
    ],
  },
  {
    name: "Black Bean Tacos",
    description: "Hearty black bean tacos with fresh avocado and lime.",
    prepTime: 15,
    calories: 360,
    difficulty: "Easy",
    instructions: "Heat black beans with cumin and chili flakes. Warm tortillas. Fill with beans, diced avocado, tomato, and cilantro. Squeeze lime over top.",
    dietTags: ["Vegetarian", "Vegan", "QuickMeal"],
    ingredients: [
      { name: "Black Beans", required: true },
      { name: "Tortilla", required: true },
      { name: "Avocado", required: true },
      { name: "Tomato", required: true },
      { name: "Lime", required: true },
      { name: "Cilantro", required: false },
      { name: "Cumin", required: false },
    ],
  },
  {
    name: "Lentil Soup",
    description: "Warming lentil soup with aromatic spices and fresh vegetables.",
    prepTime: 40,
    calories: 320,
    difficulty: "Easy",
    instructions: "Sauté onion, carrot, garlic in olive oil. Add lentils, cumin, paprika. Cover with water, bring to boil. Simmer 30 min until lentils are tender. Stir in spinach.",
    dietTags: ["Vegetarian", "Vegan", "HighProtein"],
    ingredients: [
      { name: "Lentils", required: true },
      { name: "Carrot", required: true },
      { name: "Onion", required: true },
      { name: "Spinach", required: true },
      { name: "Garlic", required: true },
      { name: "Cumin", required: false },
      { name: "Olive Oil", required: false },
    ],
  },
  {
    name: "Chickpea and Spinach Curry",
    description: "Creamy coconut chickpea curry with wilted spinach.",
    prepTime: 25,
    calories: 400,
    difficulty: "Easy",
    instructions: "Sauté onion and garlic 3 min. Add chickpeas, coconut milk, cumin, and paprika. Simmer 15 min. Stir in spinach until wilted. Serve over rice.",
    dietTags: ["Vegetarian", "Vegan", "HighProtein"],
    ingredients: [
      { name: "Chickpeas", required: true },
      { name: "Coconut Milk", required: true },
      { name: "Spinach", required: true },
      { name: "Onion", required: true },
      { name: "Garlic", required: true },
      { name: "Cumin", required: false },
      { name: "Rice", required: false },
    ],
  },
  {
    name: "Mushroom and Spinach Pasta",
    description: "Earthy mushroom pasta with garlic and wilted spinach.",
    prepTime: 20,
    calories: 430,
    difficulty: "Easy",
    instructions: "Cook pasta. Sauté mushrooms in olive oil until golden, 5 min. Add garlic and spinach, cook 2 min. Toss with pasta, squeeze lemon, top with cheese.",
    dietTags: ["Vegetarian", "QuickMeal"],
    ingredients: [
      { name: "Pasta", required: true },
      { name: "Mushrooms", required: true },
      { name: "Spinach", required: true },
      { name: "Garlic", required: true },
      { name: "Olive Oil", required: true },
      { name: "Lemon", required: false },
      { name: "Cheese", required: false },
    ],
  },
  {
    name: "Sweet Potato and Black Bean Chili",
    description: "Smoky vegetarian chili with sweet potato and black beans.",
    prepTime: 35,
    calories: 380,
    difficulty: "Easy",
    instructions: "Sauté onion and garlic. Add cubed sweet potato, black beans, tomato, cumin, paprika, and chili flakes. Add water, simmer 25 min. Top with avocado and cilantro.",
    dietTags: ["Vegetarian", "Vegan", "HighProtein"],
    ingredients: [
      { name: "Sweet Potato", required: true },
      { name: "Black Beans", required: true },
      { name: "Tomato", required: true },
      { name: "Onion", required: true },
      { name: "Cumin", required: true },
      { name: "Avocado", required: false },
      { name: "Chili Flakes", required: false },
    ],
  },
  {
    name: "Vegetable Fried Rice",
    description: "Quick vegetable fried rice with soy sauce and sesame.",
    prepTime: 15,
    calories: 350,
    difficulty: "Easy",
    instructions: "Heat sesame oil in wok. Add carrot, corn, and green beans, stir-fry 3 min. Add cold rice and soy sauce, fry 3 min. Push aside, scramble eggs, mix all.",
    dietTags: ["Vegetarian", "QuickMeal"],
    ingredients: [
      { name: "Rice", required: true },
      { name: "Eggs", required: true },
      { name: "Carrot", required: true },
      { name: "Corn", required: true },
      { name: "Soy Sauce", required: true },
      { name: "Sesame Oil", required: false },
      { name: "Green Beans", required: false },
    ],
  },
  {
    name: "Caprese Salad with Quinoa",
    description: "Fresh caprese over protein-packed quinoa.",
    prepTime: 15,
    calories: 340,
    difficulty: "Easy",
    instructions: "Cook quinoa, cool slightly. Slice tomato and cheese. Arrange over quinoa. Drizzle olive oil, top with fresh basil. Season with salt and pepper.",
    dietTags: ["Vegetarian", "QuickMeal"],
    ingredients: [
      { name: "Quinoa", required: true },
      { name: "Tomato", required: true },
      { name: "Cheese", required: true },
      { name: "Basil", required: true },
      { name: "Olive Oil", required: false },
    ],
  },
  {
    name: "Cauliflower and Chickpea Bake",
    description: "Roasted cauliflower and chickpeas with warming spices.",
    prepTime: 35,
    calories: 360,
    difficulty: "Easy",
    instructions: "Toss cauliflower florets and chickpeas with olive oil, cumin, paprika. Spread on sheet pan. Roast at 425°F for 25 min. Serve with Greek yogurt drizzle.",
    dietTags: ["Vegetarian", "HighProtein"],
    ingredients: [
      { name: "Cauliflower", required: true },
      { name: "Chickpeas", required: true },
      { name: "Olive Oil", required: true },
      { name: "Cumin", required: true },
      { name: "Paprika", required: true },
      { name: "Greek Yogurt", required: false },
    ],
  },
  {
    name: "Stuffed Bell Peppers",
    description: "Colorful bell peppers stuffed with rice, beans, and vegetables.",
    prepTime: 40,
    calories: 370,
    difficulty: "Medium",
    instructions: "Cut tops off peppers, remove seeds. Mix cooked rice, black beans, corn, tomato, cumin. Fill peppers, top with cheese. Bake at 375°F for 25 min.",
    dietTags: ["Vegetarian"],
    ingredients: [
      { name: "Bell Pepper", required: true },
      { name: "Rice", required: true },
      { name: "Black Beans", required: true },
      { name: "Corn", required: true },
      { name: "Tomato", required: true },
      { name: "Cheese", required: false },
      { name: "Cumin", required: false },
    ],
  },

  // === FISH (10) ===
  {
    name: "Lemon Garlic Salmon",
    description: "Pan-seared salmon with bright lemon garlic butter.",
    prepTime: 20,
    calories: 420,
    difficulty: "Easy",
    instructions: "Season salmon fillets. Sear skin-side down in olive oil 4 min. Flip, add garlic and lemon juice. Cook 3 min more. Serve with asparagus.",
    dietTags: ["HighProtein", "LowCarb", "QuickMeal"],
    ingredients: [
      { name: "Salmon", required: true },
      { name: "Lemon", required: true },
      { name: "Garlic", required: true },
      { name: "Olive Oil", required: true },
      { name: "Asparagus", required: false },
    ],
  },
  {
    name: "Tuna Poke Bowl",
    description: "Hawaiian-inspired poke bowl with fresh tuna and avocado.",
    prepTime: 15,
    calories: 440,
    difficulty: "Easy",
    instructions: "Cube tuna. Toss with soy sauce, sesame oil, rice vinegar. Serve over rice with avocado, cucumber, and sesame seeds.",
    dietTags: ["HighProtein", "QuickMeal"],
    ingredients: [
      { name: "Tuna", required: true },
      { name: "Rice", required: true },
      { name: "Avocado", required: true },
      { name: "Soy Sauce", required: true },
      { name: "Sesame Oil", required: true },
      { name: "Cucumber", required: false },
      { name: "Rice Vinegar", required: false },
    ],
  },
  {
    name: "Garlic Shrimp with Zucchini Noodles",
    description: "Light and flavorful garlic shrimp over spiralized zucchini.",
    prepTime: 15,
    calories: 280,
    difficulty: "Easy",
    instructions: "Spiralize zucchini. Sauté shrimp in olive oil with garlic 3 min per side. Add zucchini noodles, toss 2 min. Finish with lemon juice and chili flakes.",
    dietTags: ["HighProtein", "LowCarb", "QuickMeal"],
    ingredients: [
      { name: "Shrimp", required: true },
      { name: "Zucchini", required: true },
      { name: "Garlic", required: true },
      { name: "Olive Oil", required: true },
      { name: "Lemon", required: true },
      { name: "Chili Flakes", required: false },
    ],
  },
  {
    name: "Cod with Coconut Curry Sauce",
    description: "Flaky cod in a fragrant coconut curry broth.",
    prepTime: 25,
    calories: 380,
    difficulty: "Medium",
    instructions: "Sauté onion, garlic, ginger 3 min. Add coconut milk and cumin, simmer 5 min. Nestle cod fillets into sauce, cover, cook 10 min until flaky. Serve with rice.",
    dietTags: ["HighProtein"],
    ingredients: [
      { name: "Cod", required: true },
      { name: "Coconut Milk", required: true },
      { name: "Onion", required: true },
      { name: "Garlic", required: true },
      { name: "Ginger", required: true },
      { name: "Rice", required: false },
      { name: "Cumin", required: false },
    ],
  },
  {
    name: "Salmon and Quinoa Power Bowl",
    description: "Omega-rich salmon over quinoa with roasted vegetables.",
    prepTime: 30,
    calories: 510,
    difficulty: "Medium",
    instructions: "Cook quinoa. Roast sweet potato and broccoli at 400°F for 20 min. Pan-sear salmon 4 min per side. Assemble bowl and drizzle with lemon olive oil.",
    dietTags: ["HighProtein"],
    ingredients: [
      { name: "Salmon", required: true },
      { name: "Quinoa", required: true },
      { name: "Sweet Potato", required: true },
      { name: "Broccoli", required: true },
      { name: "Lemon", required: false },
      { name: "Olive Oil", required: false },
    ],
  },
  {
    name: "Shrimp Stir-Fry with Noodles",
    description: "Quick shrimp and vegetable stir-fry over noodles.",
    prepTime: 20,
    calories: 410,
    difficulty: "Easy",
    instructions: "Cook noodles. Stir-fry shrimp in sesame oil 2 min per side. Add bell pepper and mushrooms, cook 3 min. Toss with noodles, soy sauce, and ginger.",
    dietTags: ["HighProtein", "QuickMeal"],
    ingredients: [
      { name: "Shrimp", required: true },
      { name: "Noodles", required: true },
      { name: "Bell Pepper", required: true },
      { name: "Mushrooms", required: true },
      { name: "Soy Sauce", required: true },
      { name: "Sesame Oil", required: false },
      { name: "Ginger", required: false },
    ],
  },
  {
    name: "Baked Tilapia with Herbs",
    description: "Light and flaky baked tilapia with fresh herb topping.",
    prepTime: 20,
    calories: 260,
    difficulty: "Easy",
    instructions: "Place tilapia in baking dish. Top with olive oil, lemon juice, garlic, and parsley. Bake at 400°F for 12 min. Serve with steamed asparagus.",
    dietTags: ["HighProtein", "LowCarb", "QuickMeal"],
    ingredients: [
      { name: "Tilapia", required: true },
      { name: "Lemon", required: true },
      { name: "Olive Oil", required: true },
      { name: "Garlic", required: true },
      { name: "Parsley", required: true },
      { name: "Asparagus", required: false },
    ],
  },
  {
    name: "Tuna and White Bean Salad",
    description: "Mediterranean-inspired tuna salad with creamy white beans.",
    prepTime: 10,
    calories: 350,
    difficulty: "Easy",
    instructions: "Flake tuna into bowl. Add chickpeas, diced cucumber, tomato, and onion. Dress with olive oil, lemon juice, and parsley. Toss gently.",
    dietTags: ["HighProtein", "LowCarb", "QuickMeal"],
    ingredients: [
      { name: "Tuna", required: true },
      { name: "Chickpeas", required: true },
      { name: "Cucumber", required: true },
      { name: "Tomato", required: true },
      { name: "Olive Oil", required: true },
      { name: "Lemon", required: false },
      { name: "Onion", required: false },
    ],
  },
  {
    name: "Coconut Lime Shrimp",
    description: "Tropical coconut lime shrimp served over brown rice.",
    prepTime: 20,
    calories: 430,
    difficulty: "Easy",
    instructions: "Sauté shrimp 2 min per side. Add coconut milk, lime juice, ginger, and cilantro. Simmer 5 min. Serve over brown rice.",
    dietTags: ["HighProtein", "QuickMeal"],
    ingredients: [
      { name: "Shrimp", required: true },
      { name: "Coconut Milk", required: true },
      { name: "Lime", required: true },
      { name: "Brown Rice", required: true },
      { name: "Ginger", required: false },
      { name: "Cilantro", required: false },
    ],
  },
  {
    name: "Salmon Teriyaki with Vegetables",
    description: "Glazed teriyaki salmon with stir-fried vegetables.",
    prepTime: 25,
    calories: 460,
    difficulty: "Medium",
    instructions: "Mix soy sauce, honey, rice vinegar, ginger for glaze. Brush salmon, bake at 400°F 12 min. Stir-fry broccoli and carrot. Serve salmon over vegetables with rice.",
    dietTags: ["HighProtein"],
    ingredients: [
      { name: "Salmon", required: true },
      { name: "Soy Sauce", required: true },
      { name: "Honey", required: true },
      { name: "Rice Vinegar", required: true },
      { name: "Broccoli", required: true },
      { name: "Carrot", required: false },
      { name: "Rice", required: false },
    ],
  },

  // === EGG/TOFU (10) ===
  {
    name: "Veggie Scrambled Eggs",
    description: "Fluffy scrambled eggs loaded with fresh vegetables.",
    prepTime: 10,
    calories: 280,
    difficulty: "Easy",
    instructions: "Sauté spinach, tomato, and mushrooms 3 min. Pour in beaten eggs, gently scramble until just set. Top with cheese and chili flakes.",
    dietTags: ["Vegetarian", "LowCarb", "QuickMeal"],
    ingredients: [
      { name: "Eggs", required: true },
      { name: "Spinach", required: true },
      { name: "Tomato", required: true },
      { name: "Mushrooms", required: true },
      { name: "Cheese", required: false },
      { name: "Chili Flakes", required: false },
    ],
  },
  {
    name: "Tofu Stir-Fry",
    description: "Crispy pan-fried tofu with colorful vegetables.",
    prepTime: 25,
    calories: 340,
    difficulty: "Easy",
    instructions: "Press and cube tofu. Pan-fry in sesame oil until golden, 8 min. Add bell pepper, broccoli, and carrot. Add soy sauce and ginger. Serve over rice.",
    dietTags: ["Vegetarian", "Vegan", "HighProtein"],
    ingredients: [
      { name: "Tofu", required: true },
      { name: "Bell Pepper", required: true },
      { name: "Broccoli", required: true },
      { name: "Soy Sauce", required: true },
      { name: "Sesame Oil", required: true },
      { name: "Ginger", required: false },
      { name: "Rice", required: false },
    ],
  },
  {
    name: "Egg Fried Noodles",
    description: "Simple stir-fried noodles with scrambled eggs and vegetables.",
    prepTime: 15,
    calories: 390,
    difficulty: "Easy",
    instructions: "Cook noodles. Scramble eggs, set aside. Stir-fry cabbage and carrot 3 min. Add noodles, soy sauce, sesame oil. Fold in eggs.",
    dietTags: ["Vegetarian", "QuickMeal"],
    ingredients: [
      { name: "Noodles", required: true },
      { name: "Eggs", required: true },
      { name: "Cabbage", required: true },
      { name: "Carrot", required: true },
      { name: "Soy Sauce", required: true },
      { name: "Sesame Oil", required: false },
    ],
  },
  {
    name: "Tofu and Mushroom Rice Bowl",
    description: "Savory tofu and mushroom bowl over steamed rice.",
    prepTime: 25,
    calories: 400,
    difficulty: "Easy",
    instructions: "Press and cube tofu. Sauté mushrooms 5 min. Add tofu, cook until golden. Add soy sauce, ginger, and garlic. Serve over rice with kale.",
    dietTags: ["Vegetarian", "Vegan", "HighProtein"],
    ingredients: [
      { name: "Tofu", required: true },
      { name: "Mushrooms", required: true },
      { name: "Rice", required: true },
      { name: "Soy Sauce", required: true },
      { name: "Kale", required: true },
      { name: "Ginger", required: false },
      { name: "Garlic", required: false },
    ],
  },
  {
    name: "Shakshuka",
    description: "Eggs poached in spiced tomato sauce with peppers.",
    prepTime: 25,
    calories: 310,
    difficulty: "Medium",
    instructions: "Sauté onion and bell pepper 5 min. Add tomato, cumin, paprika, chili flakes. Simmer 10 min. Make wells, crack eggs in. Cover, cook 5 min until eggs set.",
    dietTags: ["Vegetarian", "LowCarb"],
    ingredients: [
      { name: "Eggs", required: true },
      { name: "Tomato", required: true },
      { name: "Bell Pepper", required: true },
      { name: "Onion", required: true },
      { name: "Cumin", required: true },
      { name: "Paprika", required: false },
      { name: "Chili Flakes", required: false },
    ],
  },
  {
    name: "Tofu Coconut Curry",
    description: "Silky tofu in a rich coconut curry with vegetables.",
    prepTime: 30,
    calories: 420,
    difficulty: "Medium",
    instructions: "Press and cube tofu. Sauté onion, garlic, ginger 3 min. Add coconut milk, cumin, spinach. Simmer 10 min. Add tofu, cook 5 min. Serve over rice.",
    dietTags: ["Vegetarian", "Vegan", "HighProtein"],
    ingredients: [
      { name: "Tofu", required: true },
      { name: "Coconut Milk", required: true },
      { name: "Spinach", required: true },
      { name: "Onion", required: true },
      { name: "Garlic", required: true },
      { name: "Ginger", required: true },
      { name: "Rice", required: false },
    ],
  },
  {
    name: "Egg and Avocado Toast",
    description: "Classic avocado toast topped with a perfectly fried egg.",
    prepTime: 10,
    calories: 320,
    difficulty: "Easy",
    instructions: "Toast bread. Mash avocado with lime juice and salt. Spread on toast. Fry egg sunny-side up. Place on avocado, top with chili flakes.",
    dietTags: ["Vegetarian", "QuickMeal"],
    ingredients: [
      { name: "Eggs", required: true },
      { name: "Avocado", required: true },
      { name: "Bread", required: true },
      { name: "Lime", required: false },
      { name: "Chili Flakes", required: false },
    ],
  },
  {
    name: "Tempeh Buddha Bowl",
    description: "Nourishing bowl with marinated tempeh and roasted veggies.",
    prepTime: 35,
    calories: 450,
    difficulty: "Medium",
    instructions: "Marinate sliced tempeh in soy sauce, rice vinegar, ginger 15 min. Pan-fry until crispy. Roast sweet potato and kale. Assemble bowl with quinoa and avocado.",
    dietTags: ["Vegetarian", "Vegan", "HighProtein"],
    ingredients: [
      { name: "Tempeh", required: true },
      { name: "Quinoa", required: true },
      { name: "Sweet Potato", required: true },
      { name: "Kale", required: true },
      { name: "Soy Sauce", required: true },
      { name: "Avocado", required: false },
      { name: "Rice Vinegar", required: false },
    ],
  },
  {
    name: "Egg Drop Soup",
    description: "Silky Chinese-style egg drop soup with corn.",
    prepTime: 10,
    calories: 180,
    difficulty: "Easy",
    instructions: "Bring broth to simmer. Add corn. Beat eggs with sesame oil. Slowly drizzle eggs into simmering broth while stirring. Season with soy sauce and ginger.",
    dietTags: ["Vegetarian", "LowCarb", "QuickMeal"],
    ingredients: [
      { name: "Eggs", required: true },
      { name: "Corn", required: true },
      { name: "Soy Sauce", required: true },
      { name: "Sesame Oil", required: true },
      { name: "Ginger", required: false },
    ],
  },
  {
    name: "Crispy Tofu Tacos",
    description: "Crunchy tofu tacos with fresh slaw and lime crema.",
    prepTime: 25,
    calories: 380,
    difficulty: "Easy",
    instructions: "Press and slice tofu. Coat with cornstarch and pan-fry until crispy. Shred cabbage with lime and cilantro for slaw. Assemble in tortillas with avocado.",
    dietTags: ["Vegetarian", "Vegan", "HighProtein"],
    ingredients: [
      { name: "Tofu", required: true },
      { name: "Tortilla", required: true },
      { name: "Cabbage", required: true },
      { name: "Avocado", required: true },
      { name: "Lime", required: true },
      { name: "Cilantro", required: false },
    ],
  },
];

async function seed() {
  console.log("Seeding database...");

  const dietTags = await Promise.all(
    DIET_TAGS.map((name) =>
      prisma.dietTag.upsert({
        where: { name },
        update: {},
        create: { name },
      })
    )
  );
  console.log(`  ✓ ${dietTags.length} diet tags`);

  const ingredients = await Promise.all(
    INGREDIENTS.map((ing) =>
      prisma.ingredient.upsert({
        where: { name: ing.name },
        update: { category: ing.category },
        create: ing,
      })
    )
  );
  console.log(`  ✓ ${ingredients.length} ingredients`);

  const ingredientMap = new Map(ingredients.map((i) => [i.name, i.id]));
  const dietTagMap = new Map(dietTags.map((t) => [t.name, t.id]));

  let recipeCount = 0;
  for (const r of RECIPES) {
    const recipe = await prisma.recipe.upsert({
      where: { name: r.name },
      update: {
        description: r.description,
        prepTime: r.prepTime,
        calories: r.calories,
        difficulty: r.difficulty,
        instructions: r.instructions,
      },
      create: {
        name: r.name,
        description: r.description,
        prepTime: r.prepTime,
        calories: r.calories,
        difficulty: r.difficulty,
        instructions: r.instructions,
      },
    });

    for (const ing of r.ingredients) {
      const ingredientId = ingredientMap.get(ing.name);
      if (!ingredientId) {
        console.warn(`  ⚠ Ingredient not found: ${ing.name}`);
        continue;
      }
      await prisma.recipeIngredient.upsert({
        where: {
          recipeId_ingredientId: { recipeId: recipe.id, ingredientId },
        },
        update: { required: ing.required },
        create: { recipeId: recipe.id, ingredientId, required: ing.required },
      });
    }

    for (const tagName of r.dietTags) {
      const dietTagId = dietTagMap.get(tagName);
      if (!dietTagId) {
        console.warn(`  ⚠ Diet tag not found: ${tagName}`);
        continue;
      }
      await prisma.recipeDietTag.upsert({
        where: {
          recipeId_dietTagId: { recipeId: recipe.id, dietTagId },
        },
        update: {},
        create: { recipeId: recipe.id, dietTagId },
      });
    }

    recipeCount++;
  }
  console.log(`  ✓ ${recipeCount} recipes with ingredients and diet tags`);
  console.log("Seed complete.");
}

seed()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
